version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    registries:
      - tradeshift-gcr
    schedule:
      interval: daily
registries:
  tradeshift-gcr:
    type: docker-registry
    url: 063399264027.dkr.ecr.eu-west-1.amazonaws.com
    username: _json_key
    repository: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-base/http-mockserver
