name: Pull request

on:
  pull_request:
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tradeshift/actions-docker@v1
        name: docker
        with:
          password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_NOBASE64 }}
          push: false
  tests:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Run tests
        run: docker run --rm "${{ steps.docker.outputs.image }}" npm test